# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        submodules: true

    # Runs a single command using the runners shell
    - uses: lukka/run-cmake@v2.5
      with:
        cmakeGenerator: VS17Win64
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        cmakeBuildType: Release
        buildDirectory: ${{ runner.temp }}/build
        buildWithCMake: true


    # Actual testing happening
    - name: Examine Output
      run: dir ${{ runner.temp }}\build\

    # Actual testing happening
    - name: Run Unittest
      run: ${{ runner.temp }}\build\Release\RR32CanTest.exe
